# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-29 04:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='domain',
            field=models.CharField(default=datetime.datetime(2020, 9, 29, 4, 54, 23, 721495, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
