# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-10-01 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_auth', '0004_auto_20200929_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='url',
            new_name='user',
        ),
    ]
